//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Content.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceLayerLinkResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceLayerLinkResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Content.Resources.ServiceLayerLinkResource", typeof(ServiceLayerLinkResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/document.
        /// </summary>
        internal static string addDocumentUrl {
            get {
                return ResourceManager.GetString("addDocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /admin.
        /// </summary>
        internal static string AdminUrl {
            get {
                return ResourceManager.GetString("AdminUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin/email/?emailId={0}.
        /// </summary>
        internal static string checkForMailUrl {
            get {
                return ResourceManager.GetString("checkForMailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager/{0}/employees.
        /// </summary>
        internal static string createTaskLinkUrl {
            get {
                return ResourceManager.GetString("createTaskLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/?loginUserId={0}.
        /// </summary>
        internal static string createTaskManagerUrl {
            get {
                return ResourceManager.GetString("createTaskManagerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/{0}/employees.
        /// </summary>
        internal static string createTaskUrl {
            get {
                return ResourceManager.GetString("createTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /create-user.
        /// </summary>
        internal static string createUserUrl {
            get {
                return ResourceManager.GetString("createUserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #035100.
        /// </summary>
        internal static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #350051.
        /// </summary>
        internal static string DarkVoilet {
            get {
                return ResourceManager.GetString("DarkVoilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/{0}/tasks/count.
        /// </summary>
        internal static string dashboardUrl {
            get {
                return ResourceManager.GetString("dashboardUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager/{0}/?loginUser={1}.
        /// </summary>
        internal static string deleteTaskUrl {
            get {
                return ResourceManager.GetString("deleteTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin/{0}/?loginUser={1}.
        /// </summary>
        internal static string deleteUserUrl {
            get {
                return ResourceManager.GetString("deleteUserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager/tasks/{0}/task-name.
        /// </summary>
        internal static string documentPartialViewUrl {
            get {
                return ResourceManager.GetString("documentPartialViewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/tasks/{0}.
        /// </summary>
        internal static string editTaskLinkUrl {
            get {
                return ResourceManager.GetString("editTaskLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager/{0}/?loginUser={1}.
        /// </summary>
        internal static string editTaskUrl {
            get {
                return ResourceManager.GetString("editTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin/{0}/?loginUser={1}.
        /// </summary>
        internal static string editUserDetailsUrl {
            get {
                return ResourceManager.GetString("editUserDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /employees/{0}/tasks.
        /// </summary>
        internal static string getEmployeeTasksUrl {
            get {
                return ResourceManager.GetString("getEmployeeTasksUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /employees/status.
        /// </summary>
        internal static string getStatusListUrl {
            get {
                return ResourceManager.GetString("getStatusListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /employees/{0}/tasks/count.
        /// </summary>
        internal static string getTaskCountsUrl {
            get {
                return ResourceManager.GetString("getTaskCountsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to employees/tasks/{0}.
        /// </summary>
        internal static string getTaskDetailsUrl {
            get {
                return ResourceManager.GetString("getTaskDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1dfe16.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InProgress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager/{0}/tasks.
        /// </summary>
        internal static string listTaskUrl {
            get {
                return ResourceManager.GetString("listTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /manager.
        /// </summary>
        internal static string managerUrl {
            get {
                return ResourceManager.GetString("managerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fe6b16.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /roles.
        /// </summary>
        internal static string roleUrl {
            get {
                return ResourceManager.GetString("roleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50862.
        /// </summary>
        internal static string serviceLayerUrl {
            get {
                return ResourceManager.GetString("serviceLayerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /employees/UpdateTask.
        /// </summary>
        internal static string updateTaskUrl {
            get {
                return ResourceManager.GetString("updateTaskUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /user-detail.
        /// </summary>
        internal static string userDetailUrl {
            get {
                return ResourceManager.GetString("userDetailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ab01da.
        /// </summary>
        internal static string Voilet {
            get {
                return ResourceManager.GetString("Voilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
