//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public long EmpId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Userdetail Userdetail { get; set; }
        public virtual Role Role { get; set; }
    }
}
