//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDocument
    {
        public long Id { get; set; }
        public long TaskId { get; set; }
        public string DocumentPath { get; set; }
        public long AddedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Userdetail Userdetail { get; set; }
    }
}
