//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public string Id { get; set; }
        public string TaskId { get; set; }
        public string AssignedTo { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public string ReAssignedBy { get; set; }
        public Nullable<System.DateTime> ReAssignedOn { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
