//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public string Id { get; set; }
        public string TaskId { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
    }
}
